### ISSUE TITLE
Sidebar 컴포넌트 개발

### ISSUE THREAD

**Issue by YeryunJung** [codestates-seb/seb40_pre_026#5]
### Description 
좌측 sidebar 컴포넌트 개발

### To-do
- [x] 구조 러프하게 구현
- [x] 폰트어썸 아이콘 추가
- [x] 스타일 컴포넌트 구현
- [x] 추가 CSS 적용 (26일 회의 후 크기 및 배치 적용 예정)
